server:
  port: 1314
  servlet:
    context-path: /hjj
  tomcat:
    uri-encoding: UTF-8
    basedir: /tmp/tomcat
  shutdown: graceful  #优雅关闭

param:
  param1: param1
  param2: param2
  param3: param3
